### ISSUE TITLE
Decouple from custom tracers

### ISSUE THREAD

**Issue by adriancole** [weaveworks-experiments/loki#6]
Unless I'm misunderstanding things, there's no need for a custom tracer to do what you are doing here, just a custom span transport, inverting from a push to a pull model. It seems more than reasonable to make a transport plugin that would work with existing tracers (opentracing, htrace, google-instrumentation, zipkin etc).. or am I over simplifying?

**Comment by tomwilkie** [comment]
You are spot on Adrian! That is how it works right now, the new tracer
stuff is just a helper function which sets it up for you.

**Comment by adriancole** [comment]
Cool. Good to know!
